# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StarterKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
  # Pods for StarterKit
  pod 'Firebase/Core', '~> 5.2.0'
    pod 'FirebaseAnalytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  
pod 'FBSDKCoreKit', '5.8.0'
 pod 'FBSDKLoginKit', '5.8.0'
 pod 'FBSDKShareKit', '5.8.0'
 pod 'RSKImageCropper'
 pod 'QBImagePickerController'   

end

 
